export const BUSINESS = {
  name: "Taxi Bhai",
  legalName: "Taxi Bhai Saudi Taxi Service",
  tagline: "Saudi Arabia's Most Trusted Taxi Service",
  description:
    "Taxi Bhai provides professional 24/7 taxi service across Saudi Arabia including airport transfers, Umrah transport, Ziyarat tours, VIP rides, and intercity travel between Jeddah, Makkah, Madinah, Taif, and Badr.",
  phone: "+966573067785",
  whatsapp: "+966573067785",
  email: "taxibhai.sa@gmail.com",
  website: "https://taxibhaisauditaxiservice.com",
  founded: "2019",
  country: "SA",
  currency: "SAR",
  languages: ["en", "ar"],
  geo: {
    latitude: 21.4225,
    longitude: 39.8262,
  },
  address: {
    streetAddress: "King Abdulaziz International Airport Road",
    addressLocality: "Jeddah",
    addressRegion: "Makkah Province",
    postalCode: "21421",
    addressCountry: "SA",
  },
  socialMedia: {
    whatsapp: "https://wa.me/966573067785",
  },
  rating: {
    value: 4.9,
    count: 847,
  },
  openingHours: "Mo-Su 00:00-24:00",
} as const;

export const WHATSAPP_CATALOG = {
  airportTransfer: "https://wa.me/p/23957774393831986/269874890809567",
  umrahTaxi:       "https://wa.me/p/9925568250886108/269874890809567",
  ziyaratTaxi:     "https://wa.me/p/30950141154599884/269874890809567",
  intercityTaxi:   "https://wa.me/p/25001226919465169/269874890809567",
  default:         "https://wa.me/966573067785?text=Hi%20Taxi%20Bhai%2C%20I%20want%20to%20book%20a%20taxi.",
} as const;

export const ROUTES = {
  home: "/",
  services: {
    airportTransfer: "/services/airport-transfer",
    umrahTaxi: "/services/umrah-taxi",
    ziyaratTaxi: "/services/ziyarat-taxi",
    vipTaxi: "/services/vip-taxi",
    familyTaxi: "/services/family-taxi",
    haramTransfer: "/services/haram-transfer",
    intercityTaxi: "/services/intercity-taxi",
    cityToCity: "/services/city-to-city",
  },
  locations: {
    jeddah: "/locations/jeddah",
    makkah: "/locations/makkah",
    madinah: "/locations/madinah",
    taif: "/locations/taif",
    badr: "/locations/badr",
  },
  blog: "/blog",
  static: {
    about: "/about",
    contact: "/contact",
    faq: "/faq",
    privacy: "/privacy",
  },
} as const;

export const CITIES = {
  jeddah: {
    name: "Jeddah",
    nameAr: "جدة",
    region: "Makkah Province",
    geo: { latitude: 21.4858, longitude: 39.1925 },
    population: 4697000,
    description:
      "The commercial capital of Saudi Arabia and gateway to the holy cities",
    airport: {
      name: "King Abdulaziz International Airport",
      iata: "JED",
      terminals: ["Terminal 1 (International)", "Terminal 2 (Domestic)", "Terminal 3 (Hajj)"],
    },
    landmarks: [
      "KAIA Airport",
      "King Fahd Fountain",
      "Jeddah Corniche",
      "Al-Balad Historic District",
      "Mall of Arabia",
      "Red Sea Mall",
    ],
  },
  makkah: {
    name: "Makkah",
    nameAr: "مكة المكرمة",
    region: "Makkah Province",
    geo: { latitude: 21.4225, longitude: 39.8262 },
    population: 2385509,
    description: "The holiest city in Islam, home to Masjid al-Haram",
    landmarks: [
      "Masjid al-Haram",
      "Kaaba",
      "Abraj Al-Bait (Clock Tower)",
      "Mount Arafat",
      "Mina",
      "Muzdalifah",
      "Jamarat Bridge",
      "Cave of Hira (Jabal al-Nour)",
      "Cave of Thawr",
    ],
  },
  madinah: {
    name: "Madinah",
    nameAr: "المدينة المنورة",
    region: "Madinah Province",
    geo: { latitude: 24.4539, longitude: 39.6142 },
    population: 1512724,
    description: "The City of the Prophet, second holiest city in Islam",
    airport: {
      name: "Prince Mohammad bin Abdulaziz International Airport",
      iata: "MED",
    },
    landmarks: [
      "Masjid al-Nabawi (Prophet's Mosque)",
      "Al-Baqi Cemetery",
      "Masjid Quba",
      "Masjid al-Qiblatayn",
      "Mount Uhud",
      "Al-Hijaz Railway Museum",
      "Dates Market",
    ],
  },
  taif: {
    name: "Taif",
    nameAr: "الطائف",
    region: "Makkah Province",
    geo: { latitude: 21.2703, longitude: 40.4158 },
    population: 1200000,
    description:
      "The city of roses at 1,800m elevation, known for its cool climate",
    landmarks: [
      "Al Shafa",
      "Al Hada",
      "Taif Rose Festival",
      "Shubra Palace",
      "Taif Zoo",
      "Al Rudaf Park",
    ],
  },
  badr: {
    name: "Badr",
    nameAr: "بدر",
    region: "Madinah Province",
    geo: { latitude: 23.7833, longitude: 38.7833 },
    population: 78000,
    description:
      "Historic site of the Battle of Badr, 155km from Madinah",
    landmarks: [
      "Battle of Badr Site",
      "Badr Mosque",
      "Martyrs of Badr Cemetery",
      "Badr Mountain",
    ],
  },
} as const;

export const INTERCITY_ROUTES = [
  {
    from: "jeddah",
    to: "makkah",
    fromName: "Jeddah",
    toName: "Makkah",
    slug: "jeddah-to-makkah",
    distance: 80,
    duration: "1 hour",
    durationMinutes: 60,
    highway: "Jeddah–Makkah Expressway (Route 40)",
    priceRange: { economy: 120, vip: 200 },
    description:
      "The most traveled route in Saudi Arabia, connecting Jeddah to the holy city of Makkah via the Jeddah-Makkah Expressway.",
  },
  {
    from: "jeddah",
    to: "madinah",
    fromName: "Jeddah",
    toName: "Madinah",
    slug: "jeddah-to-madinah",
    distance: 420,
    duration: "4–4.5 hours",
    durationMinutes: 255,
    highway: "Route 60 (Jeddah-Madinah Highway)",
    priceRange: { economy: 350, vip: 550 },
    description:
      "The major intercity route between Jeddah and Madinah, passing through the western Saudi highland corridor.",
  },
  {
    from: "jeddah",
    to: "taif",
    fromName: "Jeddah",
    toName: "Taif",
    slug: "jeddah-to-taif",
    distance: 90,
    duration: "1.5 hours",
    durationMinutes: 90,
    highway: "Jeddah–Taif Expressway (Route 65)",
    priceRange: { economy: 150, vip: 250 },
    description:
      "A scenic mountain route climbing from sea level to 1,800m elevation into the cool city of Taif.",
  },
  {
    from: "jeddah",
    to: "badr",
    fromName: "Jeddah",
    toName: "Badr",
    slug: "jeddah-to-badr",
    distance: 310,
    duration: "3.5 hours",
    durationMinutes: 210,
    highway: "Route 60 then Badr Road",
    priceRange: { economy: 280, vip: 450 },
    description:
      "Travel from Jeddah to the historic Badr battleground site, a major Ziyarat destination for Muslim pilgrims.",
  },
  {
    from: "makkah",
    to: "madinah",
    fromName: "Makkah",
    toName: "Madinah",
    slug: "makkah-to-madinah",
    distance: 450,
    duration: "4.5–5 hours",
    durationMinutes: 270,
    highway: "Route 60 / Haramain Highway",
    priceRange: { economy: 380, vip: 580 },
    description:
      "The sacred route between the two holiest cities in Islam, traveled by millions of pilgrims performing Umrah and Hajj.",
  },
  {
    from: "makkah",
    to: "taif",
    fromName: "Makkah",
    toName: "Taif",
    slug: "makkah-to-taif",
    distance: 75,
    duration: "1.5 hours",
    durationMinutes: 90,
    highway: "Route 40 / Makkah–Taif Road",
    priceRange: { economy: 130, vip: 220 },
    description:
      "A short mountain drive from the holy city of Makkah to the elevated resort city of Taif.",
  },
  {
    from: "makkah",
    to: "jeddah",
    fromName: "Makkah",
    toName: "Jeddah",
    slug: "makkah-to-jeddah",
    distance: 80,
    duration: "1 hour",
    durationMinutes: 60,
    highway: "Jeddah–Makkah Expressway (Route 40)",
    priceRange: { economy: 120, vip: 200 },
    description:
      "Return route from Makkah to Jeddah's airport or city center, ideal for post-Umrah airport transfers.",
  },
  {
    from: "madinah",
    to: "makkah",
    fromName: "Madinah",
    toName: "Makkah",
    slug: "madinah-to-makkah",
    distance: 450,
    duration: "4.5–5 hours",
    durationMinutes: 270,
    highway: "Route 60 / Haramain Highway",
    priceRange: { economy: 380, vip: 580 },
    description:
      "Travel from Madinah to Makkah for Umrah completion, following the Haramain corridor.",
  },
  {
    from: "madinah",
    to: "jeddah",
    fromName: "Madinah",
    toName: "Jeddah",
    slug: "madinah-to-jeddah",
    distance: 420,
    duration: "4–4.5 hours",
    durationMinutes: 255,
    highway: "Route 60 (Jeddah-Madinah Highway)",
    priceRange: { economy: 350, vip: 550 },
    description:
      "Direct taxi service from Madinah to Jeddah International Airport for pilgrim departures.",
  },
  {
    from: "madinah",
    to: "badr",
    fromName: "Madinah",
    toName: "Badr",
    slug: "madinah-to-badr",
    distance: 155,
    duration: "1.5–2 hours",
    durationMinutes: 105,
    highway: "Madinah–Badr Road (Route 340)",
    priceRange: { economy: 200, vip: 320 },
    description:
      "The most popular Ziyarat route from Madinah to Badr, site of Islam's first major battle.",
  },
  {
    from: "taif",
    to: "makkah",
    fromName: "Taif",
    toName: "Makkah",
    slug: "taif-to-makkah",
    distance: 75,
    duration: "1.5 hours",
    durationMinutes: 90,
    highway: "Route 40 / Taif-Makkah Road",
    priceRange: { economy: 130, vip: 220 },
    description:
      "Mountain descent from Taif to the holy city of Makkah for Umrah and Haram visits.",
  },
  {
    from: "taif",
    to: "jeddah",
    fromName: "Taif",
    toName: "Jeddah",
    slug: "taif-to-jeddah",
    distance: 90,
    duration: "1.5 hours",
    durationMinutes: 90,
    highway: "Jeddah–Taif Expressway (Route 65)",
    priceRange: { economy: 150, vip: 250 },
    description:
      "Descent from Taif highlands to Jeddah via the scenic Taif-Jeddah Expressway.",
  },
  // ── Airport-specific routes ──────────────────────────────────────────────
  {
    from: "jeddah",
    to: "makkah",
    fromName: "Jeddah Airport (KAIA)",
    toName: "Makkah",
    slug: "jeddah-airport-to-makkah",
    distance: 80,
    duration: "1 hour",
    durationMinutes: 60,
    highway: "Jeddah–Makkah Expressway (Route 40)",
    priceRange: { economy: 120, vip: 200 },
    description:
      "Direct airport taxi from King Abdulaziz International Airport (KAIA) to Makkah hotels and Masjid al-Haram. Flight tracking included, driver waits at arrivals.",
  },
  {
    from: "jeddah",
    to: "madinah",
    fromName: "Jeddah Airport (KAIA)",
    toName: "Madinah",
    slug: "jeddah-airport-to-madinah",
    distance: 420,
    duration: "4–4.5 hours",
    durationMinutes: 255,
    highway: "Route 60 (Jeddah-Madinah Highway)",
    priceRange: { economy: 350, vip: 550 },
    description:
      "Airport taxi from KAIA Jeddah directly to Madinah hotels and Masjid Nabawi area. Ideal for Umrah pilgrims arriving in Jeddah and heading to Madinah first.",
  },
  {
    from: "makkah",
    to: "jeddah",
    fromName: "Makkah Haram",
    toName: "Jeddah Airport (KAIA)",
    slug: "haram-to-airport",
    distance: 80,
    duration: "1 hour",
    durationMinutes: 60,
    highway: "Jeddah–Makkah Expressway (Route 40)",
    priceRange: { economy: 120, vip: 200 },
    description:
      "Transfer from Masjid al-Haram and Makkah hotels directly to Jeddah International Airport (KAIA). On-time departure guarantee for flight connections after Umrah.",
  },
] as const;

export const SERVICES = [
  {
    id: "airport-transfer",
    name: "Airport Transfer",
    slug: "airport-transfer",
    icon: "plane",
    shortDesc: "24/7 flight-tracked airport pickup and drop-off",
    fullDesc:
      "Professional airport transfer service from King Abdulaziz International Airport (KAIA) in Jeddah. We track your flight in real-time, offer meet-and-greet at arrivals, and provide on-time guaranteed departures.",
    startingPrice: 80,
    popular: true,
  },
  {
    id: "jeddah-airport-taxi",
    name: "Jeddah Airport Taxi",
    slug: "airport-transfer",
    icon: "building2",
    shortDesc: "KAIA Terminal 1, 2 & 3 specialist pickup service",
    fullDesc:
      "Dedicated taxi service for King Abdulaziz International Airport — all three terminals. Fixed pricing, no surprises.",
    startingPrice: 80,
    popular: true,
  },
  {
    id: "umrah-taxi",
    name: "Umrah Taxi",
    slug: "umrah-taxi",
    icon: "moon",
    shortDesc: "Sacred Miqat to Haram Umrah transport packages",
    fullDesc:
      "Specialized Umrah taxi packages covering airport arrival to Miqat, Haram visits, and all Umrah rituals across Makkah and Madinah.",
    startingPrice: 150,
    popular: true,
  },
  {
    id: "ziyarat-taxi",
    name: "Ziyarat Taxi",
    slug: "ziyarat-taxi",
    icon: "landmark",
    shortDesc: "Guided Islamic landmark tours in Madinah and Makkah",
    fullDesc:
      "Complete Ziyarat tour packages covering all major Islamic historical sites in Madinah (Masjid Nabawi, Uhud, Quba) and Makkah (Hira, Thawr, Arafat).",
    startingPrice: 200,
    popular: false,
  },
  {
    id: "vip-taxi",
    name: "VIP Taxi",
    slug: "vip-taxi",
    icon: "crown",
    shortDesc: "Luxury sedans and SUVs with premium chauffeur service",
    fullDesc:
      "Luxury VIP taxi service with premium vehicles (Toyota Camry, Lexus, GMC Yukon), professional chauffeurs, and concierge-level service.",
    startingPrice: 200,
    popular: false,
  },
  {
    id: "family-taxi",
    name: "Family Taxi",
    slug: "family-taxi",
    icon: "users",
    shortDesc: "Spacious family vans and safe travel for groups",
    fullDesc:
      "Family-safe taxi service with spacious vehicles, child seat availability, female-friendly drivers on request, and group pricing.",
    startingPrice: 120,
    popular: false,
  },
  {
    id: "haram-transfer",
    name: "Haram Transfer",
    slug: "haram-transfer",
    icon: "home",
    shortDesc: "Hotel-to-Haram shuttle runs in Makkah and Madinah",
    fullDesc:
      "Dedicated Haram transfer service running between hotels and Masjid al-Haram in Makkah and Masjid Nabawi in Madinah, 24 hours a day.",
    startingPrice: 30,
    popular: true,
  },
  {
    id: "intercity-taxi",
    name: "Saudi Intercity Taxi",
    slug: "intercity-taxi",
    icon: "map-pin",
    shortDesc: "City-to-city travel across the western Saudi region",
    fullDesc:
      "Fixed-price intercity taxi covering all major routes: Jeddah–Makkah, Jeddah–Madinah, Makkah–Madinah, and more.",
    startingPrice: 120,
    popular: true,
  },
] as const;
